---
resources:
  - name: nodejs-buildpack
    type: git
    source:
      uri: https://github.com/cloudfoundry/nodejs-buildpack
      branch: develop
  - name: ruby-buildpack
    type: git
    source:
      uri: https://github.com/cloudfoundry/ruby-buildpack
      branch: develop
  - name: go-buildpack
    type: git
    source:
      uri: https://github.com/cloudfoundry/go-buildpack
      branch: develop
  - name: ci-tools
    type: git
    source:
      uri: https://github.com/cloudfoundry/ci-tools
  - name: buildpacks-ci
    type: git
    source:
      uri: git@github.com:pivotal-cf/buildpacks-ci
      private_key: {{buildpacks-private-key}}
  - name: machete-firewall-test
    type: git
    source:
      uri: https://github.com/cf-buildpacks/machete-firewall-test
  - name: deployments-buildpacks
    type: git
    source:
      uri: git@github.com:pivotal-cf/deployments-buildpacks
      private_key: {{buildpacks-private-key}}
  - name: buildpack-packager
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/buildpack-packager.git
  - name: machete
    type: git
    source:
      uri: https://github.com/cf-buildpacks/machete.git
  - name: compile-extensions
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/compile-extensions.git
  - name: heroku-nanny
    type: git
    source:
      uri: https://github.com/cf-buildpacks/upstream-nanny.git
  - name: brats
    type: git
    source:
      uri: https://github.com/cloudfoundry/brats.git
groups:
- name: all-the-things
  jobs:
  - nodejs-buildpack-CF-edge
  - nodejs-buildpack-CF-LTS
  - ruby-buildpack-CF-edge
  - ruby-buildpack-CF-LTS
  - go-CF-edge
  - go-CF-LTS
  - machete-firewall-CF-edge
  - machete-firewall-CF-LTS
  - buildpack-packager
  - machete
  - compile-extensions
  - old-releases
  - heroku-nanny
  - brats-go-CF-LTS
  - brats-go-CF-edge
  - brats-python-CF-LTS
  - brats-python-CF-edge
  - brats-nodejs-CF-LTS
  - brats-nodejs-CF-edge
  - brats-php-CF-LTS
  - brats-php-CF-edge
  - brats-ruby-CF-LTS
  - brats-ruby-CF-edge
- name: nodejs-buildpack
  jobs:
  - nodejs-buildpack-CF-edge
  - nodejs-buildpack-CF-LTS
- name: machete-firewall
  jobs:
  - machete-firewall-CF-edge
  - machete-firewall-CF-LTS
- name: go
  jobs:
  - go-CF-edge
  - go-CF-LTS
- name: ruby
  jobs:
  - ruby-buildpack-CF-edge
  - ruby-buildpack-CF-LTS
- name: tooling
  jobs:
  - buildpack-packager
  - machete
  - compile-extensions
  - old-releases
  - heroku-nanny
- name: brats
  jobs:
  - brats-go-CF-LTS
  - brats-go-CF-edge
  - brats-python-CF-LTS
  - brats-python-CF-edge
  - brats-nodejs-CF-LTS
  - brats-nodejs-CF-edge
  - brats-php-CF-LTS
  - brats-php-CF-edge
  - brats-ruby-CF-LTS
  - brats-ruby-CF-edge
jobs:
  - name: nodejs-buildpack-CF-edge
    public: true
    serial: true
    serial_groups: [bp-ci-8]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: ci-tools
          trigger: false
        - get: deployments-buildpacks
          trigger: false
        - get: nodejs-buildpack
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: ci-tools
            - name: nodejs-buildpack
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/nodejs-buildpack.sh
          params:
            DEPLOYMENT_NAME: bp-ci-8
            STACKS: lucid64 cflinuxfs2
        privileged: true
  - name: nodejs-buildpack-CF-LTS
    public: true
    serial: true
    serial_groups: [bp-ci-7]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: ci-tools
          trigger: false
        - get: deployments-buildpacks
          trigger: false
        - get: nodejs-buildpack
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: ci-tools
            - name: nodejs-buildpack
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/nodejs-buildpack.sh
          params:
            DEPLOYMENT_NAME: bp-ci-7
            STACKS: lucid64
        privileged: true
  - name: ruby-buildpack-CF-edge
    public: true
    serial: true
    serial_groups: [bp-ci-8]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: ci-tools
          trigger: false
        - get: deployments-buildpacks
          trigger: false
        - get: ruby-buildpack
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: ci-tools
            - name: ruby-buildpack
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/ruby-buildpack.sh
          params:
            DEPLOYMENT_NAME: bp-ci-8
            STACKS: lucid64 cflinuxfs2
        privileged: true
  - name: ruby-buildpack-CF-LTS
    public: true
    serial: true
    serial_groups: [bp-ci-7]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: ci-tools
          trigger: false
        - get: deployments-buildpacks
          trigger: false
        - get: ruby-buildpack
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: ci-tools
            - name: ruby-buildpack
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/ruby-buildpack.sh
          params:
            DEPLOYMENT_NAME: bp-ci-7
            STACKS: lucid64
        privileged: true
  - name: go-CF-edge
    public: true
    serial: true
    serial_groups: [bp-ci-8]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: ci-tools
          trigger: false
        - get: deployments-buildpacks
          trigger: false
        - get: go-buildpack
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: ci-tools
            - name: go-buildpack
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/go-buildpack.sh
          params:
            DEPLOYMENT_NAME: bp-ci-8
            STACKS: lucid64 cflinuxfs2
        privileged: true
  - name: go-CF-LTS
    public: true
    serial: true
    serial_groups: [bp-ci-7]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: ci-tools
          trigger: false
        - get: deployments-buildpacks
          trigger: false
        - get: go-buildpack
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: ci-tools
            - name: go-buildpack
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/go-buildpack.sh
          params:
            DEPLOYMENT_NAME: bp-ci-7
            STACKS: lucid64
        privileged: true
  - name: machete-firewall-CF-edge
    public: true
    serial: true
    serial_groups: [bp-ci-8]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: ci-tools
          trigger: false
        - get: deployments-buildpacks
          trigger: false
        - get: machete-firewall-test
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: ci-tools
            - name: deployments-buildpacks
            - name: machete-firewall-test
          run:
            path: buildpacks-ci/scripts/machete-firewall.sh
          params:
            DEPLOYMENT_NAME: bp-ci-8
            STACKS: lucid64 cflinuxfs2
        privileged: true
  - name: machete-firewall-CF-LTS
    public: true
    serial: true
    serial_groups : [bp-ci-7]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: ci-tools
          trigger: false
        - get: deployments-buildpacks
          trigger: false
        - get: machete-firewall-test
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: ci-tools
            - name: deployments-buildpacks
            - name: machete-firewall-test
          run:
            path: buildpacks-ci/scripts/machete-firewall.sh
          params:
            DEPLOYMENT_NAME: bp-ci-7
            STACKS: lucid64
        privileged: true
  - name: buildpack-packager
    public: true
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: buildpack-packager
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: buildpack-packager
          run:
            path: buildpacks-ci/scripts/buildpack-packager.sh
        privileged: true
  - name: machete
    public: true
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: machete
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: machete
          run:
            path: buildpacks-ci/scripts/machete.sh
        privileged: true
  - name: compile-extensions
    public: true
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: compile-extensions
      - task: rspec
        config:
          platform: linux
          image: docker:///ruby#1.9.3-slim
          inputs:
            - name: buildpacks-ci
            - name: compile-extensions
          run:
            path: buildpacks-ci/scripts/compile-extensions.sh
        privileged: true
  - name: old-releases
    public: true
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: ci-tools
      - task: outdated_buildpack_releases
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: ci-tools
          run:
            path: buildpacks-ci/scripts/old-releases.sh
          params:
            GITHUB_TOKEN: {{buildpacks-github-token}}
        privileged: true
  - name: heroku-nanny
    public: true
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: heroku-nanny
      - task: sanity-check-upstream
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: heroku-nanny
          run:
            path: buildpacks-ci/scripts/heroku-nanny.sh
        privileged: true
  - name: brats-go-CF-LTS
    public: true
    serial: true
    serial_groups : [bp-ci-7]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: brats
          trigger: false
        - get: deployments-buildpacks
          trigger: false
      - task: bin-tests
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: brats
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/brats-go.sh
          params:
            DEPLOYMENT_NAME: bp-ci-7
        privileged: true
  - name: brats-go-CF-edge
    public: true
    serial: true
    serial_groups : [bp-ci-8]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: brats
          trigger: false
        - get: deployments-buildpacks
          trigger: false
      - task: bin-tests
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: brats
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/brats-go.sh
          params:
            DEPLOYMENT_NAME: bp-ci-8
        privileged: true
  - name: brats-python-CF-LTS
    public: true
    serial: true
    serial_groups : [bp-ci-7]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: brats
          trigger: false
        - get: deployments-buildpacks
          trigger: false
      - task: bin-tests
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: brats
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/brats-python.sh
          params:
            DEPLOYMENT_NAME: bp-ci-7
        privileged: true
  - name: brats-python-CF-edge
    public: true
    serial: true
    serial_groups : [bp-ci-8]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: brats
          trigger: false
        - get: deployments-buildpacks
          trigger: false
      - task: bin-tests
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: brats
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/brats-python.sh
          params:
            DEPLOYMENT_NAME: bp-ci-8
        privileged: true
  - name: brats-nodejs-CF-LTS
    public: true
    serial: true
    serial_groups : [bp-ci-7]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: brats
          trigger: false
        - get: deployments-buildpacks
          trigger: false
      - task: bin-tests
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: brats
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/brats-nodejs.sh
          params:
            DEPLOYMENT_NAME: bp-ci-7
        privileged: true
  - name: brats-nodejs-CF-edge
    public: true
    serial: true
    serial_groups : [bp-ci-8]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: brats
          trigger: false
        - get: deployments-buildpacks
          trigger: false
      - task: bin-tests
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: brats
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/brats-nodejs.sh
          params:
            DEPLOYMENT_NAME: bp-ci-8
        privileged: true
  - name: brats-php-CF-LTS
    public: true
    serial: true
    serial_groups : [bp-ci-7]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: brats
          trigger: false
        - get: deployments-buildpacks
          trigger: false
      - task: bin-tests
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: brats
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/brats-php.sh
          params:
            DEPLOYMENT_NAME: bp-ci-7
        privileged: true
  - name: brats-php-CF-edge
    public: true
    serial: true
    serial_groups : [bp-ci-8]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: brats
          trigger: false
        - get: deployments-buildpacks
          trigger: false
      - task: bin-tests
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: brats
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/brats-php.sh
          params:
            DEPLOYMENT_NAME: bp-ci-8
        privileged: true
  - name: brats-ruby-CF-LTS
    public: true
    serial: true
    serial_groups : [bp-ci-7]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: brats
          trigger: false
        - get: deployments-buildpacks
          trigger: false
      - task: bin-tests
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: brats
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/brats-ruby.sh
          params:
            DEPLOYMENT_NAME: bp-ci-7
        privileged: true
  - name: brats-ruby-CF-edge
    public: true
    serial: true
    serial_groups : [bp-ci-8]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: brats
          trigger: false
        - get: deployments-buildpacks
          trigger: false
      - task: bin-tests
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: brats
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/brats-ruby.sh
          params:
            DEPLOYMENT_NAME: bp-ci-8
        privileged: true
