---
resources:
  - name: nodejs-buildpack
    type: git
    source:
      uri: https://github.com/cloudfoundry/nodejs-buildpack
      branch: develop
  - name: ruby-buildpack
    type: git
    source:
      uri: https://github.com/cloudfoundry/ruby-buildpack
      branch: develop
  - name: go-buildpack
    type: git
    source:
      uri: https://github.com/cloudfoundry/go-buildpack
      branch: develop
  - name: ci-tools
    type: git
    source:
      uri: https://github.com/cloudfoundry/ci-tools
  - name: buildpacks-ci
    type: git
    source:
      uri: git@github.com:pivotal-cf/buildpacks-ci
      private_key: {{buildpacks-private-key}}
  - name: machete-firewall-test
    type: git
    source:
      uri: https://github.com/cf-buildpacks/machete-firewall-test
  - name: deployments-buildpacks
    type: git
    source:
      uri: git@github.com:pivotal-cf/deployments-buildpacks
      private_key: {{buildpacks-private-key}}
  - name: buildpack-packager
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/buildpack-packager.git
groups:
- name: all-the-things
  jobs:
  - nodejs-buildpack-CF-edge
  - nodejs-buildpack-CF-LTS
  - ruby-buildpack-CF-edge
  - ruby-buildpack-CF-LTS
  - go-CF-edge
  - go-CF-LTS
  - machete-firewall-CF-edge
  - machete-firewall-CF-LTS
- name: nodejs-buildpack
  jobs:
  - nodejs-buildpack-CF-edge
  - nodejs-buildpack-CF-LTS
- name: machete-firewall
  jobs:
  - machete-firewall-CF-edge
  - machete-firewall-CF-LTS
- name: go
  jobs:
  - go-CF-edge
  - go-CF-LTS
- name: ruby
  jobs:
  - ruby-buildpack-CF-edge
  - ruby-buildpack-CF-LTS
- name: tooling
  jobs:
  - buildpack-packager
jobs:
  - name: nodejs-buildpack-CF-edge
    public: true
    serial: true
    serial_groups: [bp-ci-8]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: ci-tools
          trigger: false
        - get: deployments-buildpacks
          trigger: false
        - get: nodejs-buildpack
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: ci-tools
            - name: nodejs-buildpack
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/nodejs-buildpack.sh
          params:
            DEPLOYMENT_NAME: bp-ci-8
            STACKS: lucid64 cflinuxfs2
        privileged: true
  - name: nodejs-buildpack-CF-LTS
    public: true
    serial: true
    serial_groups: [bp-ci-7]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: ci-tools
          trigger: false
        - get: deployments-buildpacks
          trigger: false
        - get: nodejs-buildpack
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: ci-tools
            - name: nodejs-buildpack
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/nodejs-buildpack.sh
          params:
            DEPLOYMENT_NAME: bp-ci-7
            STACKS: lucid64
        privileged: true
  - name: ruby-buildpack-CF-edge
    public: true
    serial: true
    serial_groups: [bp-ci-8]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: ci-tools
          trigger: false
        - get: deployments-buildpacks
          trigger: false
        - get: ruby-buildpack
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: ci-tools
            - name: ruby-buildpack
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/ruby-buildpack.sh
          params:
            DEPLOYMENT_NAME: bp-ci-8
            STACKS: lucid64 cflinuxfs2
        privileged: true
  - name: ruby-buildpack-CF-LTS
    public: true
    serial: true
    serial_groups: [bp-ci-7]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: ci-tools
          trigger: false
        - get: deployments-buildpacks
          trigger: false
        - get: ruby-buildpack
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: ci-tools
            - name: ruby-buildpack
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/ruby-buildpack.sh
          params:
            DEPLOYMENT_NAME: bp-ci-7
            STACKS: lucid64
        privileged: true
  - name: go-CF-edge
    public: true
    serial: true
    serial_groups: [bp-ci-8]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: ci-tools
          trigger: false
        - get: deployments-buildpacks
          trigger: false
        - get: go-buildpack
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: ci-tools
            - name: go-buildpack
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/go-buildpack.sh
          params:
            DEPLOYMENT_NAME: bp-ci-8
            STACKS: lucid64 cflinuxfs2
        privileged: true
  - name: go-CF-LTS
    public: true
    serial: true
    serial_groups: [bp-ci-7]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: ci-tools
          trigger: false
        - get: deployments-buildpacks
          trigger: false
        - get: go-buildpack
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: ci-tools
            - name: go-buildpack
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/go-buildpack.sh
          params:
            DEPLOYMENT_NAME: bp-ci-7
            STACKS: lucid64
        privileged: true
  - name: machete-firewall-CF-edge
    public: true
    serial: true
    serial_groups: [bp-ci-8]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: ci-tools
          trigger: false
        - get: deployments-buildpacks
          trigger: false
        - get: machete-firewall-test
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: ci-tools
            - name: deployments-buildpacks
            - name: machete-firewall-test
          run:
            path: buildpacks-ci/scripts/machete-firewall.sh
          params:
            DEPLOYMENT_NAME: bp-ci-8
            STACKS: lucid64 cflinuxfs2
        privileged: true
  - name: machete-firewall-CF-LTS
    public: true
    serial: true
    serial_groups : [bp-ci-7]
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: ci-tools
          trigger: false
        - get: deployments-buildpacks
          trigger: false
        - get: machete-firewall-test
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: ci-tools
            - name: deployments-buildpacks
            - name: machete-firewall-test
          run:
            path: buildpacks-ci/scripts/machete-firewall.sh
          params:
            DEPLOYMENT_NAME: bp-ci-7
            STACKS: lucid64
        privileged: true
  - name: buildpack-packager
    public: true
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
          trigger: false
        - get: buildpack-packager
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: buildpacks-ci
            - name: buildpack-packager
          run:
            path: buildpacks-ci/scripts/buildpack-packager.sh
        privileged: true
