---
platform: linux
image: docker:///cfbuildpacks/ci
inputs:
  - name: ci-develop
params:
  TERM: xterm-color
  CI_USERNAME:
  CI_PASSWORD:
run:
  path: bash
  args:
    - "-c"
    - cd ci-develop && ./scripts/fly-login $CI_USERNAME $CI_PASSWORD && bundle && rspec
