---
platform: linux
image: docker:///cfbuildpacks/ci
run:
  path: bash
  args:
    - -c
    - |
      curl -f -L -o cf-bosh-release-artifacts/release.tgz https://bosh.io/d/github.com/cloudfoundry/cf-release?v=$RELEASE_VERSION
outputs:
  - name: cf-bosh-release-artifacts
params:
  RELEASE_VERSION:
