---
platform: linux
image: docker:///cfbuildpacks/ci
run:
  path: bash
  args: ['git', 'clone', '--branch', 'v208', '--depth', '1', 'https://github.com/cloudfoundry/cf-release', '.', '&&', './update' ]

