---
platform: linux
image: docker:///cfbuildpacks/ci
inputs:
  - name: buildpacks-ci
  - name: stack-s3
  - name: version
  - name: stacks-release
outputs:
  - name: stacks-release
run:
  path: buildpacks-ci/scripts/stacks/create-bosh-stacks-release.sh
