---
platform: linux
image: docker:///cfbuildpacks/ci
inputs:
  - name: buildpacks-ci
  - name: stacks
  - name: version
outputs:
  - name: stacks-artifacts
  - name: receipt-artifacts
run:
  path: buildpacks-ci/scripts/stacks/make-rootfs
