---
platform: linux
image: docker:///cfbuildpacks/ci
inputs:
  - name: buildpacks-ci
  - name: diego-release
  - name: cflinuxfs2-rootfs-release
  - name: deployments-buildpacks
outputs:
  - name: rootfs-smoke-test-manifest-artifacts
run:
  path: buildpacks-ci/scripts/make-rootfs-smoke-test-manifest
params:
  DEPLOYMENT_NAME:
