---
platform: linux
image: docker:///cfbuildpacks/ci#buildpack
inputs:
  - name: buildpacks-ci
  - name: ci-tools
  - name: buildpack
  - name: deployments-buildpacks
run:
  path: buildpacks-ci/scripts/release/pivnet_fat_buildpack.sh
