---
platform: linux
image: docker:///cfbuildpacks/ci
inputs:
  - name: buildpacks-ci
  - name: deployments-buildpacks
outputs:
  - name: deployments-buildpacks-artifacts
run:
  path: buildpacks-ci/scripts/recreate-bosh-lite
params:
  DEPLOYMENT_NAME:
  PASSWORD:
