---
platform: linux
image: docker:///cfbuildpacks/ci
inputs:
  - name: buildpacks-ci
  - name: deployments-buildpacks
  - name: pivotal-buildpacks
  - name: pivotal-buildpacks-cached
  - name: buildpack
  - name: cf-environments
run:
  path: buildpacks-ci/scripts/release/test_buildpack
