---
platform: linux
image: docker:///cfbuildpacks/ci
inputs:
  - name: buildpacks-ci
  - name: buildpacks-pivnet-uploader
  - name: pivotal-buildpacks-cached
  - name: finalize-buildpack
run:
  path: buildpacks-ci/scripts/release/upload_to_pivnet
