---
platform: linux
image: docker:///cfbuildpacks/ci
inputs:
  - name: buildpacks-ci
  - name: ci-tools
  - name: pivotal-buildpacks-cached
  - name: buildpack
  - name: cf-release
run:
  path: buildpacks-ci/scripts/release/upload_to_cf_release.sh
