---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cats-concourse-task

inputs:
- name: wats
- name: integration-config
outputs:
- name: wats-trace-output

run:
  path: bash
  args:
    - "-cl"
    - "buildpacks-ci/tasks/run-wats/run.sh"

params:
  NODES: 12
  CONFIG_FILE_PATH: integration_config.json
  SKIP_REGEXP:
  CAPTURE_LOGS: false
