---
resources:
  - name: buildpacks-pivnet-uploader
    type: git
    source:
      uri: git@github.com:pivotal-cf/buildpacks-pivnet-uploader
      private_key: {{buildpacks-pivnet-uploader-private-key}}
  - name: buildpacks-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/buildpacks-ci
  - name: cf-edge-environments
    type: pool
    source:
      branch: resource-pools
      pool: cf-edge-environments
      private_key: {{resource-pools-private-key}}
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
  - name: cf-lts-environments
    type: pool
    source:
      branch: resource-pools
      pool: cf-lts-environments
      private_key: {{resource-pools-private-key}}
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
  - name: deployments-buildpacks
    type: git
    source:
      uri: git@github.com:pivotal-cf/deployments-buildpacks
      private_key: {{deployments-private-key}}
  - name: compile-extensions
    type: git
    source:
      uri: https://github.com/cloudfoundry/compile-extensions.git
  - name: buildpack
    type: git
    source:
      uri: git@github.com:cloudfoundry/<%= language %>-buildpack.git
      private_key: {{<%= language %>-buildpack-private-key}}
      branch: develop
  - name: buildpack-master
    type: git
    source:
      uri: git@github.com:cloudfoundry/<%= language %>-buildpack.git
      private_key: {{<%= language %>-buildpack-private-key}}
      branch: master
  - name: pivotal-buildpack
    type: s3
    source:
      bucket: pivotal-buildpacks
      regexp: <%= language %>_buildpack-v(.*).zip
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}
  - name: pivotal-buildpack-cached
    type: s3
    source:
      bucket: pivotal-buildpacks
      regexp: <%= language %>_buildpack-cached-v(.*).zip
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}
  - name: buildpack-github-release
    type: github-release
    source:
      user: cloudfoundry
      repository: <%= language %>-buildpack
      access_token: {{buildpacks-github-token}}
  - name: buildpack-checksums
    type: git
    source:
      uri: git@github.com:pivotal-cf-experimental/buildpack-checksums.git
      private_key: {{buildpack-checksums-private-key}}
      branch: master
  - name: brats
    type: git
    source:
      uri: https://github.com/cloudfoundry/brats.git
  - name: failure-alert
    type: slack-notification
    source:
      url: {{concourse-job-failure-notifications-slack-webhook}}
  - name: buildpack-releases
    type: git
    source:
      uri: git@github.com:pivotal-cf-experimental/buildpack-releases.git
      private_key: {{buildpack-releases-private-key}}
      branch: master
  - name: version
    type: semver
    source:
      bucket: pivotal-buildpacks
      key: versions/<%= language %>-buildpack
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}
jobs:
  <% if language == "php" %>
  - name: ensure-manifest-has-modules
    serial: true
    plan:
      - get: buildpacks-ci
      - get: buildpack
        trigger: true
      - task: load-modules
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
            - name: buildpack
          run :
            path: bash
            args:
              - -c
              - "cd buildpack && ./bin/populate-modules-in-manifest && (git commit -am 'Updated manifest with supported PHP modules' || true)"
      - put: buildpack
        params:
          repository: load-modules/buildpack
          rebase: true
  <% end %>
  - name: detect-new-buildpack-and-upload-artifacts
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: buildpack
          resource: buildpack-master
          trigger: true
      - do:
        - task: detect-and-upload
          file: buildpacks-ci/tasks/detect-and-upload.yml
          privileged: true
        - put: pivotal-buildpack
          params:
            from: detect-and-upload/buildpack/.*_buildpack-v(.*).zip
            to: /experimental-buildpacks/<%= language %>/
        - put: pivotal-buildpack-cached
          params:
            from: detect-and-upload/buildpack/.*_buildpack-cached-v(.*).zip
            to: /experimental-buildpacks/<%= language %>/
        on_failure:
          put: failure-alert
          params:
            text: "<%= language %>-buildpack detect-new-buildpack-and-upload-artifacts job on Concourse failed! \n Check: https://buildpacks.ci.cf-app.com/pipelines/<%= language %>-buildpack/jobs/detect-new-buildpack-and-upload-artifacts"
            channel: {{concourse-job-failure-notifications-slack-channel}}
            username: concourse
            icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
  - name: buildpack-CF-edge-master
    serial: true
    plan:
      - put: cf-environments
        resource: cf-edge-environments
        params:
          acquire: true
      - aggregate:
        - get: buildpacks-ci
        - get: deployments-buildpacks
        - get: buildpack
          passed: [ "detect-new-buildpack-and-upload-artifacts" ]
          resource: buildpack-master
          trigger: true
        - get: pivotal-buildpacks
          resource: pivotal-buildpack
          passed: [ "detect-new-buildpack-and-upload-artifacts" ]
          trigger: true
        - get: pivotal-buildpacks-cached
          resource: pivotal-buildpack-cached
          passed: [ "detect-new-buildpack-and-upload-artifacts" ]
          trigger: true
      - do:
        - task: rspec
          file: buildpacks-ci/tasks/test-buildpack.yml
          config:
            params:
              STACKS: cflinuxfs2
              COMPOSER_GITHUB_OAUTH_TOKEN: {{composer-github-oauth-token}}
              CF_PASSWORD: {{ci-cf-password}}
              CF_EDGE: 'true'
          privileged: true
          ensure:
            put: cf-edge-environments
            params:
              release: cf-environments
        on_failure:
          put: failure-alert
          params:
            text: "<%= language %>-buildpack CF-edge-master job on Concourse failed! \n Check: https://buildpacks.ci.cf-app.com/pipelines/<%= language %>-buildpack/jobs/buildpack-CF-edge-master"
            channel: {{concourse-job-failure-notifications-slack-channel}}
            username: concourse
            icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
  - name: buildpack-CF-LTS-master
    serial: true
    plan:
      - put: cf-environments
        resource: cf-lts-environments
        params:
          acquire: true
      - aggregate:
        - get: buildpacks-ci
        - get: deployments-buildpacks
        - get: buildpack
          passed: [ "detect-new-buildpack-and-upload-artifacts" ]
          resource: buildpack-master
          trigger: true
        - get: pivotal-buildpacks
          resource: pivotal-buildpack
          passed: [ "detect-new-buildpack-and-upload-artifacts" ]
          trigger: true
        - get: pivotal-buildpacks-cached
          resource: pivotal-buildpack-cached
          passed: [ "detect-new-buildpack-and-upload-artifacts" ]
          trigger: true
      - do:
        - task: rspec
          file: buildpacks-ci/tasks/test-buildpack.yml
          config:
            params:
              STACKS: cflinuxfs2
              COMPOSER_GITHUB_OAUTH_TOKEN: {{composer-github-oauth-token}}
              CF_PASSWORD: {{ci-cf-password}}
          privileged: true
          ensure:
            put: cf-lts-environments
            params:
              release: cf-environments
        on_failure:
          put: failure-alert
          params:
            text: "<%= language %>-buildpack CF-LTS-master job on Concourse failed! \n Check: https://buildpacks.ci.cf-app.com/pipelines/<%= language %>-buildpack/jobs/buildpack-CF-LTS-master"
            channel: {{concourse-job-failure-notifications-slack-channel}}
            username: concourse
            icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
  - name: buildpack-release
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: pivotal-buildpacks-cached
          resource: pivotal-buildpack-cached
          passed: [ "buildpack-CF-LTS-master", "buildpack-CF-edge-master" ]
          trigger: true
        - get: buildpack
          passed: [ "buildpack-CF-LTS-master", "buildpack-CF-edge-master" ]
          resource: buildpack-master
          trigger: true
      - task: check tag not already added
        file: buildpacks-ci/tasks/check-tag-not-already-added.yml
      - put: buildpack-master
        params:
          repository: buildpack
          tag: buildpack/VERSION
          tag_prefix: v
  - name: version-bump
    serial: true
    plan:
      - get: buildpack
        passed: [ "buildpack-release" ]
        resource: buildpack-master
        trigger: true
      - put: version
        params:
          file: buildpack/VERSION
  - name: bosh-release
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: s3
          resource: pivotal-buildpack-cached
          passed: [ buildpack-release ]
        - get: version
          passed: [ version-bump ]
        - get: release
          resource: buildpack-releases
      - do:
        - task: run-both-bosh-scripts
          file: buildpacks-ci/tasks/create-bosh-release.yml
          config:
            params:
              ACCESS_KEY_ID: {{pivotal-buildpacks-s3-access-key}}
              SECRET_ACCESS_KEY: {{pivotal-buildpacks-s3-secret-key}}
              BLOB_NAME: <%= language %>-buildpack
              BLOB_GLOB: ../s3/<%= language %>_buildpack-cached-*.zip
              RELEASE_NAME: <%= language %>-buildpack-release
              RELEASE_DIR: release/<%= language %>-buildpack-release
        - put: buildpack-releases
          params:
            repository: run-both-bosh-scripts/release
            rebase: true
        on_failure:
          put: failure-alert
          params:
            text: "<%= language %>-buildpack bosh-release job on Concourse failed! \n Check: https://buildpacks.ci.cf-app.com/pipelines/<%= language %>-buildpack/jobs/bosh-release"
            channel: {{concourse-job-failure-notifications-slack-channel}}
            username: concourse
            icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
  - name: buildpack-to-github
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: pivotal-buildpacks-cached
          resource: pivotal-buildpack-cached
          passed: [ buildpack-release ]
        - get: buildpack
          resource: buildpack-master
          passed: [ buildpack-release ]
        - get: buildpack-checksums
      - task: finalize-buildpack
        file: buildpacks-ci/tasks/finalize-buildpack.yml
        privileged: true
      - task: commit-shas
        file: buildpacks-ci/tasks/commit-shas.yml
        privileged: true
      - put: buildpack-checksums
        params:
          repository: commit-shas/buildpack-checksums
          rebase: true
      - put: buildpack-github-release
        params:
          name: finalize-buildpack/tag
          tag: finalize-buildpack/tag
          body: finalize-buildpack/buildpack/RECENT_CHANGES
          globs:
            - finalize-buildpack/pivotal-buildpacks-cached/*_buildpack-cached-v*.zip
            - finalize-buildpack/pivotal-buildpacks-cached/*_buildpack-cached-v*.zip.SHA256SUM.txt
  - name: buildpack-to-pivnet
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: buildpacks-pivnet-uploader
        - get: pivotal-buildpacks-cached
          resource: pivotal-buildpack-cached
          passed: [ buildpack-release ]
        - get: buildpack
          resource: buildpack-master
          passed: [ buildpack-release ]
      - task: finalize-buildpack
        file: buildpacks-ci/tasks/finalize-buildpack.yml
        privileged: true
      - task: upload to pivnet
        file: buildpacks-ci/tasks/upload-to-pivnet.yml
        config:
          params:
            AWS_ACCESS_KEY_ID: {{pivnet-access-key}}
            AWS_SECRET_ACCESS_KEY: {{pivnet-secret-key}}
            PIVNET_S3_BUCKET: pivotalnetwork
            PIVNET_ADDRESS: https://network.pivotal.io/
            PIVNET_APIKEY: {{pivnet-apikey}}
            PIVNET_PRODUCT_NAME: {{pivnet-product-name}}
            GITHUB_URL: https://github.com/cloudfoundry/<%= language %>-buildpack
        privileged: true
  - name: edge-DEA
    serial: true
    plan:
      - put: cf-environments
        resource: cf-edge-environments
        params:
          claim: bp-ci-8
      - aggregate:
        - get: buildpacks-ci
        - get: deployments-buildpacks
        - get: brats
        - get: buildpack
          trigger: true
      - do:
        - task: rspec
          file: buildpacks-ci/tasks/test-buildpack.yml
          config:
            params:
              STACKS: cflinuxfs2
              COMPOSER_GITHUB_OAUTH_TOKEN: {{composer-github-oauth-token}}
              CF_PASSWORD: {{ci-cf-password}}
              CF_EDGE: 'true'
          privileged: true
<% unless language == "binary" %>
        - task: brats
          file: buildpacks-ci/tasks/run-brats.yml
          config:
            params:
              BRATS_BRANCH: develop
              CI_CF_USERNAME: {{ci-cf-username}}
              CI_CF_PASSWORD: {{ci-cf-password}}
              LANGUAGE: <%= language %>
<% end %>
        on_failure:
          put: failure-alert
          params:
            text: "<%= language %>-buildpack edge-DEA job on Concourse failed! \n Check: https://buildpacks.ci.cf-app.com/pipelines/<%= language %>-buildpack/jobs/edge-DEA"
            channel: {{concourse-job-failure-notifications-slack-channel}}
            username: concourse
            icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        ensure:
          put: cf-edge-environments
          params:
            release: cf-environments
  - name: edge-diego
    serial: true
    plan:
      - put: cf-environments
        resource: cf-edge-environments
        params:
          claim: bp-ci-8b
      - aggregate:
        - get: buildpacks-ci
        - get: deployments-buildpacks
        - get: brats
        - get: buildpack
          trigger: true
      - do:
        - task: rspec
          file: buildpacks-ci/tasks/test-buildpack.yml
          config:
            params:
              STACKS: cflinuxfs2
              COMPOSER_GITHUB_OAUTH_TOKEN: {{composer-github-oauth-token}}
              CF_PASSWORD: {{ci-cf-password}}
              CF_EDGE: 'true'
          privileged: true
<% unless language == "binary" %>
        - task: brats
          file: buildpacks-ci/tasks/run-brats.yml
          config:
            params:
              BRATS_BRANCH: develop
              CI_CF_USERNAME: {{ci-cf-username}}
              CI_CF_PASSWORD: {{ci-cf-password}}
              LANGUAGE: <%= language %>
<% end %>
        on_failure:
          put: failure-alert
          params:
            text: "<%= language %>-buildpack edge-diego job on Concourse failed! \n Check: https://buildpacks.ci.cf-app.com/pipelines/<%= language %>-buildpack/jobs/edge-diego"
            channel: {{concourse-job-failure-notifications-slack-channel}}
            username: concourse
            icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        ensure:
          put: cf-edge-environments
          params:
            release: cf-environments
  - name: buildpack-CF-LTS
    serial: true
    plan:
      - put: cf-environments
        resource: cf-lts-environments
        params:
          acquire: true
      - aggregate:
        - get: buildpacks-ci
        - get: deployments-buildpacks
        - get: brats
        - get: buildpack
          trigger: true
      - do:
        - task: rspec
          file: buildpacks-ci/tasks/test-buildpack.yml
          config:
            params:
              STACKS: cflinuxfs2
              COMPOSER_GITHUB_OAUTH_TOKEN: {{composer-github-oauth-token}}
              CF_PASSWORD: {{ci-cf-password}}
          privileged: true
        - task: brats
          file: buildpacks-ci/tasks/run-brats.yml
          config:
            params:
              BRATS_BRANCH: develop
              CI_CF_USERNAME: {{ci-cf-username}}
              CI_CF_PASSWORD: {{ci-cf-password}}
              LANGUAGE: <%= language %>
        on_failure:
          put: failure-alert
          params:
            text: "<%= language %>-buildpack CF-LTS job on Concourse failed! \n Check: https://buildpacks.ci.cf-app.com/pipelines/<%= language %>-buildpack/jobs/buildpack-CF-LTS"
            channel: {{concourse-job-failure-notifications-slack-channel}}
            username: concourse
            icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        ensure:
          put: cf-lts-environments
          params:
            release: cf-environments
<% unless language == "binary" %>
  - name: update-compile-extensions
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: compile-extensions
          trigger: true
        - get: buildpack
      - task: update-compile-extensions
        file: buildpacks-ci/tasks/update-compile-extensions.yml
        privileged: true
      - put: buildpack
        params:
          repository: update-compile-extensions/buildpack
          rebase: true
<% end %>
