resources:
  - name: binary-builder
    type: git
    source:
      private_key: {{buildpacks-private-key}}
      uri: git@github.com:pivotal-cf/binary-builder.git
  - name: binary-builder-compiler-cache
    type: s3
    source:
      bucket: pivotal-buildpacks
      versioned_file: ccache.tgz
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}
  - name: buildpacks-ci
    type: git
    source:
      private_key: {{buildpacks-private-key}}
      uri: git@github.com:pivotal-cf/buildpacks-ci
  - name: nginx-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-private-key}}
      uri: git@github.com:pivotal-cf/buildpacks-ci.git
      paths: [ nginx-builds.yml ]
  - name: php-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-private-key}}
      uri: git@github.com:pivotal-cf/buildpacks-ci.git
      paths: [ php-builds.yml ]
  - name: nodejs-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-private-key}}
      uri: git@github.com:pivotal-cf/buildpacks-ci.git
      paths: [ nodejs-builds.yml ]
  - name: ruby-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-private-key}}
      uri: git@github.com:pivotal-cf/buildpacks-ci.git
      paths: [ ruby-builds.yml ]
  - name: jruby-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-private-key}}
      uri: git@github.com:pivotal-cf/buildpacks-ci.git
      paths: [ jruby-builds.yml ]
  - name: httpd-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-private-key}}
      uri: git@github.com:pivotal-cf/buildpacks-ci.git
      paths: [ httpd-builds.yml ]
  - name: python-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-private-key}}
      uri: git@github.com:pivotal-cf/buildpacks-ci.git
      paths: [ python-builds.yml ]

jobs:
  - name: binary-builder
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: binary-builder
          trigger: true
        - get: binary-builder-compiler-cache
      - task: rspec
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
            - name: binary-builder-compiler-cache
          run:
            path: buildpacks-ci/scripts/binary-builder.sh
        privileged: true
      - put: binary-builder-compiler-cache
        params:
          from: rspec/ccache.tgz
  - name: build-php
    serial: true
    plan:
      - aggregate:
        - get: builds-yaml
          resource: php-builds
          trigger: true
        - get: binary-builder
          passed: [binary-builder]
          trigger: true
        - get: buildpacks-ci
      - task: build-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
            - name: builds-yaml
          run:
            path: buildpacks-ci/scripts/build-binary.rb
          params:
            BINARY_NAME: php
        privileged: true
      - task: push-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: build-binary
            - name: buildpacks-ci
          run:
            path: buildpacks-ci/scripts/push-binary.rb
          params:
            BINARY_NAME: php
            AWS_ACCESS_KEY_ID: {{pivotal-buildpacks-s3-access-key}}
            AWS_SECRET_ACCESS_KEY: {{pivotal-buildpacks-s3-secret-key}}
            AWS_DEFAULT_REGION: us-east-1
        privileged: true
      - put: php-builds
        params:
          repository: build-binary/builds-yaml
          rebase: true
  - name: build-jruby
    serial: true
    plan:
      - aggregate:
        - get: builds-yaml
          resource: jruby-builds
          trigger: true
        - get: binary-builder
          passed: [binary-builder]
          trigger: true
        - get: buildpacks-ci
      - task: build-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
            - name: builds-yaml
          run:
            path: buildpacks-ci/scripts/build-binary.rb
          params:
            BINARY_NAME: jruby
        privileged: true
      - task: push-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: build-binary
            - name: buildpacks-ci
          run:
            path: buildpacks-ci/scripts/push-binary.rb
          params:
            BINARY_NAME: jruby
            AWS_ACCESS_KEY_ID: {{pivotal-buildpacks-s3-access-key}}
            AWS_SECRET_ACCESS_KEY: {{pivotal-buildpacks-s3-secret-key}}
            AWS_DEFAULT_REGION: us-east-1
        privileged: true
      - put: jruby-builds
        params:
          repository: build-binary/builds-yaml
          rebase: true
  - name: build-httpd
    serial: true
    plan:
      - aggregate:
        - get: builds-yaml
          resource: httpd-builds
          trigger: true
        - get: binary-builder
          passed: [binary-builder]
          trigger: true
        - get: buildpacks-ci
      - task: build-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
            - name: builds-yaml
          run:
            path: buildpacks-ci/scripts/build-binary.rb
          params:
            BINARY_NAME: httpd
        privileged: true
      - task: push-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: build-binary
            - name: buildpacks-ci
          run:
            path: buildpacks-ci/scripts/push-binary.rb
          params:
            BINARY_NAME: httpd
            AWS_ACCESS_KEY_ID: {{pivotal-buildpacks-s3-access-key}}
            AWS_SECRET_ACCESS_KEY: {{pivotal-buildpacks-s3-secret-key}}
            AWS_DEFAULT_REGION: us-east-1
        privileged: true
      - put: httpd-builds
        params:
          repository: build-binary/builds-yaml
          rebase: true
  - name: build-python
    serial: true
    plan:
      - aggregate:
        - get: builds-yaml
          resource: python-builds
          trigger: true
        - get: binary-builder
          passed: [binary-builder]
          trigger: true
        - get: buildpacks-ci
      - task: build-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
            - name: builds-yaml
          run:
            path: buildpacks-ci/scripts/build-binary.rb
          params:
            BINARY_NAME: python
      - task: push-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: build-binary
            - name: buildpacks-ci
          run:
            path: buildpacks-ci/scripts/push-binary.rb
          params:
            BINARY_NAME: python
            AWS_ACCESS_KEY_ID: {{pivotal-buildpacks-s3-access-key}}
            AWS_SECRET_ACCESS_KEY: {{pivotal-buildpacks-s3-secret-key}}
            AWS_DEFAULT_REGION: us-east-1
        privileged: true
      - put: python-builds
        params:
          repository: build-binary/builds-yaml
          rebase: true
  - name: build-ruby
    serial: true
    plan:
      - aggregate:
        - get: builds-yaml
          resource: ruby-builds
          trigger: true
        - get: binary-builder
          passed: [binary-builder]
          trigger: true
        - get: buildpacks-ci
      - task: build-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
            - name: builds-yaml
          run:
            path: buildpacks-ci/scripts/build-binary.rb
          params:
            BINARY_NAME: ruby
      - task: push-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: build-binary
            - name: buildpacks-ci
          run:
            path: buildpacks-ci/scripts/push-binary.rb
          params:
            BINARY_NAME: ruby
            AWS_ACCESS_KEY_ID: {{pivotal-buildpacks-s3-access-key}}
            AWS_SECRET_ACCESS_KEY: {{pivotal-buildpacks-s3-secret-key}}
            AWS_DEFAULT_REGION: us-east-1
        privileged: true
      - put: ruby-builds
        params:
          repository: build-binary/builds-yaml
          rebase: true
  - name: build-nodejs
    serial: true
    plan:
      - aggregate:
        - get: builds-yaml
          resource: nodejs-builds
          trigger: true
        - get: binary-builder
          passed: [binary-builder]
          trigger: true
        - get: buildpacks-ci
      - task: build-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
            - name: builds-yaml
          run:
            path: buildpacks-ci/scripts/build-binary.rb
          params:
            BINARY_NAME: node
      - task: push-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: build-binary
            - name: buildpacks-ci
          run:
            path: buildpacks-ci/scripts/push-binary.rb
          params:
            BINARY_NAME: node
            AWS_ACCESS_KEY_ID: {{pivotal-buildpacks-s3-access-key}}
            AWS_SECRET_ACCESS_KEY: {{pivotal-buildpacks-s3-secret-key}}
            AWS_DEFAULT_REGION: us-east-1
        privileged: true
      - put: nodejs-builds
        params:
          repository: build-binary/builds-yaml
          rebase: true
  - name: build-nginx
    serial: true
    plan:
      - aggregate:
        - get: builds-yaml
          resource: nginx-builds
          trigger: true
        - get: binary-builder
          passed: [binary-builder]
          trigger: true
        - get: buildpacks-ci
      - task: build-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
            - name: builds-yaml
          run:
            path: buildpacks-ci/scripts/build-binary.rb
          params:
            BINARY_NAME: nginx
      - task: push-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: build-binary
            - name: buildpacks-ci
          run:
            path: buildpacks-ci/scripts/push-binary.rb
          params:
            BINARY_NAME: nginx
            AWS_ACCESS_KEY_ID: {{pivotal-buildpacks-s3-access-key}}
            AWS_SECRET_ACCESS_KEY: {{pivotal-buildpacks-s3-secret-key}}
            AWS_DEFAULT_REGION: us-east-1
        privileged: true
      - put: nginx-builds
        params:
          repository: build-binary/builds-yaml
          rebase: true
