resources:
  - name: binary-builder
    type: git
    source:
      private_key: {{buildpacks-private-key}}
      uri: git@github.com:pivotal-cf/binary-builder.git
  - name: binary-builder-compiler-cache
    type: s3
    source:
      bucket: pivotal-buildpacks
      versioned_file: ccache.tgz
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}
  - name: buildpacks-ci
    type: git
    source:
      private_key: {{buildpacks-private-key}}
      uri: git@github.com:pivotal-cf/buildpacks-ci
  - name: node-interpreter
    type: s3
    source:
      bucket: pivotal-buildpacks
      regexp: node-(.*)-linux-x64.tar.gz
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}
  - name: nginx-binary
    type: s3
    source:
      bucket: pivotal-buildpacks
      regexp: nginx-(.*)-linux-x64.tgz
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}

jobs:
  - name: binary-builder
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: binary-builder
          trigger: true
        - get: binary-builder-compiler-cache
      - task: rspec
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
            - name: binary-builder-compiler-cache
          run:
            path: buildpacks-ci/scripts/binary-builder.sh
        privileged: true
      - put: binary-builder-compiler-cache
        params:
          from: rspec/ccache.tgz
  - name: build-node
    plan:
      - aggregate:
        - get: binary-builder
          passed: [binary-builder]
        - get: buildpacks-ci
      - task: build-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
          run:
            path: buildpacks-ci/scripts/build-binary.sh
          params:
            BINARY_NAME: node
            BINARY_VERSION: 0.12.2
      - put: node-interpreter
        params:
          from: binary-builder/node-(.*)-linux-x64.tar.gz
          to: /concourse-binaries/nodejs/
  - name: build-nginx
    plan:
      - aggregate:
        - get: binary-builder
          passed: [binary-builder]
        - get: buildpacks-ci
      - task: build-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
          run:
            path: buildpacks-ci/scripts/build-binary.sh
          params:
            BINARY_NAME: nginx
            BINARY_VERSION: 1.7.10
      - put: nginx-binary
        params:
          from: binary-builder/nginx-(.*)-linux-x64.tgz
          to: /concourse-binaries/nginx/
