resources:
  - name: binary-builder
    type: git
    source:
      private_key: {{buildpacks-private-key}}
      uri: git@github.com:pivotal-cf/binary-builder.git
  - name: binary-builder-builds
    type: git
    source:
      branch: binary-builds
      private_key: {{buildpacks-private-key}}
      uri: git@github.com:pivotal-cf/buildpacks-ci.git
  - name: binary-builder-compiler-cache
    type: s3
    source:
      bucket: pivotal-buildpacks
      versioned_file: ccache.tgz
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}
  - name: buildpacks-ci
    type: git
    source:
      private_key: {{buildpacks-private-key}}
      uri: git@github.com:pivotal-cf/buildpacks-ci
  - name: node-interpreter
    type: s3
    source:
      bucket: pivotal-buildpacks
      regexp: node-(.*)-linux-x64.tar.gz
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}
  - name: php-interpreter
    type: s3
    source:
      bucket: pivotal-buildpacks
      regexp: php-(.*)-linux-x64.tgz
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}
  - name: jruby-interpreter
    type: s3
    source:
      bucket: pivotal-buildpacks
      regexp: jruby(?:9000)?-(.*)-linux-x64.tgz
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}
  - name: httpd-binary
    type: s3
    source:
      bucket: pivotal-buildpacks
      regexp: httpd-(.*)-linux-x64.tgz
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}
  - name: python-interpreter
    type: s3
    source:
      bucket: pivotal-buildpacks
      regexp: python-(.*)-linux-x64.tgz
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}
  - name: ruby-interpreter
    type: s3
    source:
      bucket: pivotal-buildpacks
      regexp: ruby-(.*)-linux-x64.tgz
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}
  - name: nginx-binary
    type: s3
    source:
      bucket: pivotal-buildpacks
      regexp: nginx-(.*)-linux-x64.tgz
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}

jobs:
  - name: binary-builder
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: binary-builder
          trigger: true
        - get: binary-builder-compiler-cache
      - task: rspec
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
            - name: binary-builder-compiler-cache
          run:
            path: buildpacks-ci/scripts/binary-builder.sh
        privileged: true
      - put: binary-builder-compiler-cache
        params:
          from: rspec/ccache.tgz
  - name: build-php
    serial: true
    plan:
      - aggregate:
        - get: builds-yaml
          resource: binary-builder-builds
          trigger: true
        - get: binary-builder
          passed: [binary-builder]
          trigger: true
        - get: buildpacks-ci
      - task: build-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
            - name: builds-yaml
          run:
            path: buildpacks-ci/scripts/build-binary.rb
          params:
            BINARY_NAME: php
        privileged: true
      - put: binary-builder-builds
        params:
          repository: build-binary/builds-yaml
          rebase: true
  - name: build-jruby
    serial: true
    plan:
      - aggregate:
        - get: builds-yaml
          resource: binary-builder-builds
          trigger: true
        - get: binary-builder
          passed: [binary-builder]
          trigger: true
        - get: buildpacks-ci
      - task: build-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
            - name: builds-yaml
          run:
            path: buildpacks-ci/scripts/build-binary.rb
          params:
            BINARY_NAME: jruby
        privileged: true
      - put: binary-builder-builds
        params:
          repository: build-binary/builds-yaml
          rebase: true
  - name: build-httpd
    serial: true
    plan:
      - aggregate:
        - get: builds-yaml
          resource: binary-builder-builds
          trigger: true
        - get: binary-builder
          passed: [binary-builder]
          trigger: true
        - get: buildpacks-ci
      - task: build-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
            - name: builds-yaml
          run:
            path: buildpacks-ci/scripts/build-binary.rb
          params:
            BINARY_NAME: httpd
        privileged: true
      - put: binary-builder-builds
        params:
          repository: build-binary/builds-yaml
          rebase: true
  - name: build-python
    serial: true
    plan:
      - aggregate:
        - get: builds-yaml
          resource: binary-builder-builds
          trigger: true
        - get: binary-builder
          passed: [binary-builder]
          trigger: true
        - get: buildpacks-ci
      - task: build-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
            - name: builds-yaml
          run:
            path: buildpacks-ci/scripts/build-binary.rb
          params:
            BINARY_NAME: python
      - put: binary-builder-builds
        params:
          repository: build-binary/builds-yaml
          rebase: true
  - name: build-ruby
    serial: true
    plan:
      - aggregate:
        - get: builds-yaml
          resource: binary-builder-builds
          trigger: true
        - get: binary-builder
          passed: [binary-builder]
          trigger: true
        - get: buildpacks-ci
      - task: build-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
            - name: builds-yaml
          run:
            path: buildpacks-ci/scripts/build-binary.rb
          params:
            BINARY_NAME: ruby
      - put: binary-builder-builds
        params:
          repository: build-binary/builds-yaml
          rebase: true
  - name: build-node
    serial: true
    plan:
      - aggregate:
        - get: builds-yaml
          resource: binary-builder-builds
          trigger: true
        - get: binary-builder
          passed: [binary-builder]
          trigger: true
        - get: buildpacks-ci
      - task: build-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
            - name: builds-yaml
          run:
            path: buildpacks-ci/scripts/build-binary.rb
          params:
            BINARY_NAME: node
      - put: binary-builder-builds
        params:
          repository: build-binary/builds-yaml
          rebase: true
  - name: build-nginx
    serial: true
    plan:
      - aggregate:
        - get: builds-yaml
          resource: binary-builder-builds
          trigger: true
        - get: binary-builder
          passed: [binary-builder]
          trigger: true
        - get: buildpacks-ci
      - task: build-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: binary-builder
            - name: buildpacks-ci
            - name: builds-yaml
          run:
            path: buildpacks-ci/scripts/build-binary.rb
          params:
            BINARY_NAME: nginx
      - task: push-binary
        config:
          platform: linux
          image: docker:///cloudfoundry/cflinuxfs2
          inputs:
            - name: build-binary
            - name: buildpacks-ci
          run:
            path: buildpacks-ci/scripts/push-binary.rb
          params:
            BINARY_NAME: nginx
            AWS_ACCESS_KEY_ID: {{pivotal-buildpacks-s3-access-key}}
            AWS_SECRET_ACCESS_KEY: {{pivotal-buildpacks-s3-secret-key}}
            AWS_DEFAULT_REGION: us-east-1
        privileged: true
      - put: binary-builder-builds
        params:
          repository: build-binary/builds-yaml
          rebase: true
