resources:
  - name: bp-ci-8-cf-deployment
    type: bosh-deployment
    source:
      target: https://ec2-52-4-139-56.compute-1.amazonaws.com:25555
      username: admin
      password: {{bosh-lite-password}}
      deployment: cf-warden
      ignore_ssl: true
  - name: deployments-buildpacks
    type: git
    source:
      uri: git@github.com:pivotal-cf/deployments-buildpacks
      private_key: {{buildpacks-private-key}}
      branch: master
  - name: bosh-lite
    type: git
    source:
      uri: https://github.com/cf-buildpacks/bosh-lite
      branch: first-instance
  - name: buildpacks-ci
    type: git
    source:
      uri: git@github.com:pivotal-cf/buildpacks-ci
      private_key: {{buildpacks-private-key}}
  - name: cf-release-github
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-release
  - name: cf-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/cf-release
jobs:
  - name: deploy-cf-to-bp-ci-8
    serial: true
    plan:
      - aggregate:
        - get: deployments-buildpacks
        - get: cf-release
        - get: bosh-lite
        - get: buildpacks-ci
        - get: cf-release-github
          params: { submodules: [src/loggregator] }
      - task: generate-manifest
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci#buildpack
          inputs:
            - name: bosh-lite
            - name: deployments-buildpacks
            - name: buildpacks-ci
            - name: cf-release-github
              path: cf-release
          run:
            path: buildpacks-ci/scripts/generate-cf-manifest
          params:
            DEPLOYMENT_NAME: bp-ci-8
        privileged: true
      - put: deployments-buildpacks
        params:
          repository: generate-manifest/deployments-buildpacks
      - put: bp-ci-8-cf-deployment
        params:
          manifest: deployments-buildpacks/deployments/bp-ci-8/manifest.yml
          stemcells: []
          releases: [cf-release/*.tgz]
