resources:
  - name: bp-ci-8-cf-deployment
    type: bosh-deployment
    source:
      target: https://bp-ci-8.cf-app.com:25555
      username: admin
      password: {{bosh-lite-password}}
      deployment: cf-warden
      ignore_ssl: true
  - name: deployments-buildpacks
    type: git
    source:
      uri: git@github.com:pivotal-cf/deployments-buildpacks
      private_key: {{deployments-private-key}}
      branch: master
  - name: bosh-lite
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-lite
  - name: buildpacks-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/buildpacks-ci
  - name: bosh-cf-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/cf-release
  - name: resource-pools
    type: git
    source:
      uri: git@github.com:cloudfoundry/buildpacks-ci
      branch: resource-pools
      private_key: {{resource-pools-private-key}}

jobs:
  - name: deploy-cf-to-bp-ci-8
    serial: true
    plan:
      - aggregate:
        - get: resource-pools
        - get: buildpacks-ci
      - task: claim-from-pool
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
            - name: resource-pools
          run:
            path: buildpacks-ci/scripts/claim-resource
            args: ['cf-edge-environments', 'bp-ci-8']
      - put: resource-pools
        params:
          repository: claim-from-pool/resource-pools
      - aggregate:
        - get: deployments-buildpacks
        - get: bosh-cf-release
        - get: bosh-lite
        - get: buildpacks-ci
        - task: cf-release
          file: buildpacks-ci/tasks/cf-release-edge.yml
      - task: generate-manifest
        file: buildpacks-ci/tasks/make-manifest.yml
        config:
          params:
            DEPLOYMENT_NAME: bp-ci-8
            CF_CI_PASSWORD: {{ci-cf-password}}
        privileged: true
      - put: deployments-buildpacks
        params:
          repository: generate-manifest/deployments-buildpacks
      - put: bp-ci-8-cf-deployment
        params:
          manifest: deployments-buildpacks/deployments/bp-ci-8/manifest.yml
          stemcells: []
          releases: [bosh-cf-release/*.tgz]
      - task: unclaim-from-pool
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
            - name: resource-pools
          run:
            path: buildpacks-ci/scripts/unclaim-resource
            args: ['cf-edge-environments', 'bp-ci-8']
      - put: resource-pools
        params:
          repository: unclaim-from-pool/resource-pools
