resources:
  - name: bp-ci-8b-cf-deployment
    type: bosh-deployment
    source:
      target: https://ec2-52-6-187-239.compute-1.amazonaws.com:25555
      username: admin
      password: {{bosh-lite-password}}
      deployment: cf-warden
      ignore_ssl: true
  - name: deployments-buildpacks
    type: git
    source:
      uri: git@github.com:pivotal-cf/deployments-buildpacks
      private_key: {{deployments-private-key}}
      branch: master
  - name: bosh-lite
    type: git
    source:
      uri: https://github.com/cf-buildpacks/bosh-lite
      branch: first-instance
  - name: buildpacks-ci
    type: git
    source:
      uri: git@github.com:pivotal-cf/buildpacks-ci
      private_key: {{buildpacks-ci-private-key}}
  - name: bosh-cf-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/cf-release
jobs:
  - name: deploy-cf-to-bp-ci-8b
    serial: true
    plan:
      - aggregate:
        - get: deployments-buildpacks
        - get: bosh-cf-release
        - get: bosh-lite
        - get: buildpacks-ci
        - task: cf-release
          config:
            platform: linux
            image: docker:///cfbuildpacks/ci#buildpack
            run:
              path: git
              args: ['clone', '--branch', 'v212', '--depth', '1', '--recursive', 'https://github.com/cloudfoundry/cf-release', '.']
      - task: generate-manifest
        file: buildpacks-ci/tasks/make-manifest.yml
        config:
          params:
            DEPLOYMENT_NAME: bp-ci-8b
            CF_CI_PASSWORD: {{ci-cf-password}}
        privileged: true
      - put: deployments-buildpacks
        params:
          repository: generate-manifest/deployments-buildpacks
      - put: bp-ci-8b-cf-deployment
        params:
          manifest: deployments-buildpacks/deployments/bp-ci-8b/manifest.yml
          stemcells: []
          releases: [bosh-cf-release/*.tgz]
