resources:
  - name: ci-master
    type: git
    source:
      uri: git@github.com:cloudfoundry/buildpacks-ci
      branch: master
      private_key: {{buildpacks-ci-master-private-key}}
  - name: ci-develop
    type: git
    source:
      uri: https://github.com/cloudfoundry/buildpacks-ci
      branch: develop
jobs:
  - name: test-merge-to-master
    serial: true
    plan:
      - aggregate:
        - get: ci-master
        - get: buildpacks-ci
          resource: ci-develop
          trigger: true
      - task: rspec
        file: buildpacks-ci/tasks/buildpacks-ci.yml
        config:
          params:
            CI_USERNAME: {{ci-username}}
            CI_PASSWORD: {{ci-password}}
        privileged: true
      - task: merge
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: ci-master
          run:
            path: bash
            args:
              - -c
              - "cd ci-master && git merge --ff-only origin/develop"
      - put: ci-master
        params:
          repository: merge/ci-master
          rebase: true
