---
resources:
  - name: master
    type: git
    source:
      uri: git@github.com:pivotal-cf-experimental/buildpack-checksums.git
      private_key: {{buildpack-checksums-private-key}}
      branch: master
  - name: gh-pages
    type: git
    source:
      uri: git@github.com:pivotal-cf-experimental/buildpack-checksums.git
      private_key: {{buildpack-checksums-private-key}}
      branch: gh-pages

jobs:
  - name: build-site
    plan:
      - aggregate:
        - get: master
          trigger: true
        - get: gh-pages
      - task: run-tests
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: master
          run:
            path: bash
            args:
              - -c
              - |
                cd master
                gem install bundle
                bundle
                rspec

      - task: build-site
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: master
            - name: gh-pages
          outputs:
            - name: gh-pages-artifacts
          run:
            path: bash
            args:
              - -c
              - |
                pushd master
                  ./generate.rb ../gh-pages
                popd

                pushd gh-pages
                  git add -A
                  git commit -m 'Update site'
                popd

                rsync -a gh-pages/ gh-pages-artifacts
        privileged: true

      - put: gh-pages
        params:
          repository: gh-pages-artifacts
          rebase: true
