resources:
  - name: buildpacks-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/buildpacks-ci
      branch: master
jobs:
  - name: rspec
    serial: true
    plan:
      - get: buildpacks-ci
        trigger: true
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
          params:
            FLYRC: {{buildpacks-flyrc}}
          run:
            path: bash
            args:
              - "-c"
              - (echo "$FLYRC" > ~/.flyrc) && cd buildpacks-ci && bundle && rspec
        privileged: true
