resources:
  - name: ci-master
    type: git
    source:
      uri: git@github.com:cloudfoundry/buildpacks-ci
      branch: master
      private_key: {{buildpacks-ci-master-private-key}}
  - name: ci-develop
    type: git
    source:
      uri: https://github.com/cloudfoundry/buildpacks-ci
      branch: develop
jobs:
  - name: merge-to-master
    serial: true
    plan:
      - aggregate:
        - get: ci-master
        - get: buildpacks-ci
          resource: ci-develop
          trigger: true
      - task: rspec
        file: buildpacks-ci/tasks/buildpacks-ci.yml
        config:
          params:
            CI_USERNAME: {{ci-username}}
            CI_PASSWORD: {{ci-password}}
        privileged: true
      - put: ci-master
        params:
          repository: rspec/buildpacks-ci
          rebase: true
      - task: concourse2tracker
        file: buildpacks-ci/tasks/concourse2tracker.yml
        config:
          params:
            RESOURCE_DIR: buildpacks-ci/
            PROJECT_ID: 1042066
            TRACKER_API_TOKEN: {{pivotal-tracker-api-token}}
