resources:
  - name: buildpacks-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/buildpacks-ci
      branch: master
jobs:
  - name: rspec
    serial: true
    plan:
      - get: buildpacks-ci
        trigger: true
      - task: rspec
        file: buildpacks-ci/tasks/buildpacks-ci.yml
        config:
          params:
            CI_USERNAME: {{ci-username}}
            CI_PASSWORD: {{ci-password}}
        privileged: true
