---
resources:
  - name: buildpacks-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/buildpacks-ci
  - name: bosh-lite
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-lite
  - name: cf-release-runtime-passed
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-release
      branch: runtime-passed
  - name: cf-release-develop
    type: git
    source:
      uri: git@github.com:cloudfoundry/cf-release
      branch: develop
      private_key: {{cf-release-private-key}}
  - name: lite-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
  - name: deployments-buildpacks
    type: git
    source:
      uri: git@github.com:pivotal-cf/deployments-buildpacks
      private_key: {{deployments-private-key}}
      branch: master
  - name: cf-release-ci-8-cf-deployment
    type: bosh-deployment
    source:
      target: https://ec2-52-2-48-11.compute-1.amazonaws.com:25555
      username: admin
      password: {{bosh-lite-password}}
      deployment: cf-warden
      ignore_ssl: true
  - name: go-buildpack-github-release
    type: github-release
    source:
      user: cloudfoundry
      repository: go-buildpack
      access_token: {{buildpacks-github-token}}
  - name: python-buildpack-github-release
    type: github-release
    source:
      user: cloudfoundry
      repository: python-buildpack
      access_token: {{buildpacks-github-token}}
  - name: nodejs-buildpack-github-release
    type: github-release
    source:
      user: cloudfoundry
      repository: nodejs-buildpack
      access_token: {{buildpacks-github-token}}
  - name: ruby-buildpack-github-release
    type: github-release
    source:
      user: cloudfoundry
      repository: ruby-buildpack
      access_token: {{buildpacks-github-token}}
  - name: php-buildpack-github-release
    type: github-release
    source:
      user: cloudfoundry
      repository: php-buildpack
      access_token: {{buildpacks-github-token}}
  - name: staticfile-buildpack-github-release
    type: github-release
    source:
      user: cloudfoundry
      repository: staticfile-buildpack
      access_token: {{buildpacks-github-token}}
  - name: binary-buildpack-github-release
    type: github-release
    source:
      user: cloudfoundry
      repository: binary-buildpack
      access_token: {{buildpacks-github-token}}

jobs:
  - name: deploy-cf-to-cf-release-ci-8
    serial: true
    serial_groups: [ cf-release-ci-8 ]
    plan:
      - aggregate:
        - get: deployments-buildpacks
        - get: bosh-lite
        - get: buildpacks-ci
        - get: cf-release
          resource: cf-release-runtime-passed
        - get: lite-stemcell
        - get: go-buildpack-github-release
        - get: python-buildpack-github-release
        - get: nodejs-buildpack-github-release
        - get: ruby-buildpack-github-release
        - get: php-buildpack-github-release
        - get: staticfile-buildpack-github-release
        - get: binary-buildpack-github-release
      - task: generate-manifest
        file: buildpacks-ci/tasks/make-manifest.yml
        config:
          params:
            DEPLOYMENT_NAME: cf-release-ci-8
            CF_CI_PASSWORD: {{ci-cf-password}}
        privileged: true
      - put: deployments-buildpacks
        params:
          repository: generate-manifest/deployments-buildpacks
      - task: create-cf-release
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
            - name: cf-release
            - name: go-buildpack-github-release
            - name: python-buildpack-github-release
            - name: nodejs-buildpack-github-release
            - name: ruby-buildpack-github-release
            - name: php-buildpack-github-release
            - name: staticfile-buildpack-github-release
            - name: binary-buildpack-github-release
          run:
            path: buildpacks-ci/scripts/release/cf/create-release
        privileged: true
      - put: cf-release-ci-8-cf-deployment
        params:
          manifest: deployments-buildpacks/deployments/cf-release-ci-8/manifest.yml
          stemcells: [lite-stemcell/*.tgz]
          releases: [create-cf-release/cf-release/dev_releases/cf/*.tgz]

  - name: cats
    serial: true
    serial_groups: [ cf-release-ci-8 ]
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: cf-release-runtime-passed
          passed: [ deploy-cf-to-cf-release-ci-8 ]
          trigger: true
        - get: deployments-buildpacks
        - get: go-buildpack-github-release
          passed: [ deploy-cf-to-cf-release-ci-8 ]
        - get: nodejs-buildpack-github-release
          passed: [ deploy-cf-to-cf-release-ci-8 ]
        - get: python-buildpack-github-release
          passed: [ deploy-cf-to-cf-release-ci-8 ]
        - get: ruby-buildpack-github-release
          passed: [ deploy-cf-to-cf-release-ci-8 ]
        - get: php-buildpack-github-release
          passed: [ deploy-cf-to-cf-release-ci-8 ]
        - get: staticfile-buildpack-github-release
          passed: [ deploy-cf-to-cf-release-ci-8 ]
        - get: binary-buildpack-github-release
          passed: [ deploy-cf-to-cf-release-ci-8 ]
      - task: cats
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
            - name: cf-release-runtime-passed
              path: cf-release
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/cats
          params:
            DEPLOYMENT_NAME: cf-release-ci-8
            CI_CF_USERNAME: {{ci-cf-username}}
            CI_CF_PASSWORD: {{ci-cf-password}}
        privileged: true
