---
resources:
  - name: buildpacks-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/buildpacks-ci
  - name: deployments-buildpacks
    type: git
    source:
      uri: git@github.com:pivotal-cf/deployments-buildpacks
      private_key: {{deployments-private-key}}
  - name: buildpack-packager
    type: git
    source:
      uri: git@github.com:cloudfoundry/buildpack-packager.git
      branch: master
      private_key: {{buildpack-packager-private-key}}
  - name: buildpack-packager-github-release
    type: github-release
    source:
      user: cloudfoundry
      repository: buildpack-packager
      access_token: {{buildpacks-github-token}}
  - name: machete
    type: git
    source:
      uri: https://github.com/cloudfoundry/machete.git
  - name: compile-extensions
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/compile-extensions.git
  - name: cf-release
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-release
  - name: nanny-time-resource
    type: time
    source:
      interval: 12h
      start: 7:00 -0400
      stop: 12:00 -0400
jobs:
  - name: buildpack-packager-specs
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: buildpack-packager
          trigger: true
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
            - name: buildpack-packager
          run:
            path: buildpacks-ci/scripts/buildpack-packager.sh
        privileged: true
  - name: buildpack-packager-tag
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: buildpack-packager
          passed: [ buildpack-packager-specs ]
      - task: bump version and push up tag
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
            - name: buildpack-packager
          outputs:
            - name: buildpack-packager-artifacts
          run:
            path: buildpacks-ci/scripts/release/buildpack-packager/bump-version
      - put: buildpack-packager
        params:
          repository: buildpack-packager-artifacts
          tag: buildpack-packager-artifacts/VERSION
          tag_prefix: v
  - name: buildpack-packager-release
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: buildpack-packager
          passed: [ buildpack-packager-tag ]
          trigger: true
      - task: create new release
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
            - name: buildpack-packager
          outputs:
            - name: buildpack-packager-artifacts
          run:
            path: buildpacks-ci/scripts/release/buildpack-packager/finalize-buildpack-packager
        privileged: true
      - put: buildpack-packager-github-release
        params:
          name: buildpack-packager-artifacts/tag
          tag: buildpack-packager-artifacts/tag
          globs:
            - buildpack-packager-artifacts/buildpack-packager-v*.zip
            - buildpack-packager-artifacts/buildpack-packager-v*.tar.gz
  - name: machete
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: machete
          trigger: true
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
            - name: machete
          run:
            path: buildpacks-ci/scripts/machete.sh
        privileged: true
  - name: compile-extensions
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: compile-extensions
          trigger: true
      - task: rspec
        config:
          platform: linux
          image: docker:///ruby#2.3.0
          inputs:
            - name: buildpacks-ci
            - name: compile-extensions
          run:
            path: buildpacks-ci/scripts/compile-extensions.sh
        privileged: true
  - name: heroku-nanny
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: nanny-time-resource
          trigger: true
      - task: sanity-check-upstream
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
          run:
            path: buildpacks-ci/scripts/sanity-check-upstream
