---
resources:
  - name: ci-tools
    type: git
    source:
      uri: https://github.com/cloudfoundry/ci-tools
  - name: buildpacks-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/buildpacks-ci
  - name: machete-firewall-test
    type: git
    source:
      uri: https://github.com/cf-buildpacks/machete-firewall-test
  - name: deployments-buildpacks
    type: git
    source:
      uri: git@github.com:pivotal-cf/deployments-buildpacks
      private_key: {{deployments-private-key}}
  - name: buildpack-packager
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/buildpack-packager.git
  - name: machete
    type: git
    source:
      uri: https://github.com/cf-buildpacks/machete.git
  - name: compile-extensions
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/compile-extensions.git
  - name: heroku-nanny
    type: git
    source:
      uri: https://github.com/cf-buildpacks/upstream-nanny.git
  - name: cf-release
    type: git
    source:
      uri: https://github.com/cf-buildpacks/cf-release
  - name: nanny-time-resource
    type: time
    source:
      interval: 12h
      start: 7:00 -0400
      stop: 12:00 -0400
  - name: cf-edge-environments
    type: pool
    source:
      branch: resource-pools
      pool: cf-edge-environments
      private_key: {{resource-pools-private-key}}
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
  - name: cf-lts-environments
    type: pool
    source:
      branch: resource-pools
      pool: cf-lts-environments
      private_key: {{resource-pools-private-key}}
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
jobs:
  - name: machete-firewall-CF-edge
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: ci-tools
        - get: deployments-buildpacks
        - get: buildpack
          resource: machete-firewall-test
        - task: cf-environments
          config:
            platform: linux
            image: docker:///cfbuildpacks/ci
            run: { path: true }
      - task: rspec
        file: buildpacks-ci/tasks/test-buildpack.yml
        config:
          params:
            STACKS: cflinuxfs2
            CF_PASSWORD: {{ci-cf-password}}
            DEPLOYMENT_NAME: bp-ci-8
        privileged: true
      - task: rspec-8b
        file: buildpacks-ci/tasks/test-buildpack.yml
        config:
          params:
            STACKS: cflinuxfs2
            CF_PASSWORD: {{ci-cf-password}}
            DEPLOYMENT_NAME: bp-ci-8b
        privileged: true
  - name: machete-firewall-CF-LTS
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: ci-tools
        - get: deployments-buildpacks
        - get: buildpack
          resource: machete-firewall-test
        - task: cf-environments
          config:
            platform: linux
            image: docker:///cfbuildpacks/ci
            run: { path: true }
      - task: rspec
        file: buildpacks-ci/tasks/test-buildpack.yml
        config:
          params:
            STACKS: cflinuxfs2
            CF_PASSWORD: {{ci-cf-password}}
            DEPLOYMENT_NAME: bp-ci-7
        privileged: true
      - task: rspec-7b
        file: buildpacks-ci/tasks/test-buildpack.yml
        config:
          params:
            STACKS: cflinuxfs2
            CF_PASSWORD: {{ci-cf-password}}
            DEPLOYMENT_NAME: bp-ci-7b
        privileged: true
  - name: buildpack-packager
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: buildpack-packager
          trigger: true
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
            - name: buildpack-packager
          run:
            path: buildpacks-ci/scripts/buildpack-packager.sh
        privileged: true
  - name: machete
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: machete
          trigger: true
      - task: rspec
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
            - name: machete
          run:
            path: buildpacks-ci/scripts/machete.sh
        privileged: true
  - name: compile-extensions
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: compile-extensions
          trigger: true
      - task: rspec
        config:
          platform: linux
          image: docker:///ruby#1.9.3-slim
          inputs:
            - name: buildpacks-ci
            - name: compile-extensions
          run:
            path: buildpacks-ci/scripts/compile-extensions.sh
        privileged: true
  - name: heroku-nanny
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: nanny-time-resource
          trigger: true
      - task: sanity-check-upstream
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
          run:
            path: buildpacks-ci/scripts/sanity-check-upstream
