---
resources:
  - name: monday-funday
    type: cron
    source:
      expression: 0 7 * * 1
      location: America/New_York
  - name: check-interval
    type: cron
    source:
      expression: "0 * * * *"
      location: America/New_York
  - name: buildpacks-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/buildpacks-ci
  - name: new-releases
    type: git
    source:
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
      branch: new-release-notifications
      private_key: {{buildpacks-ci-binary-builds-private-key}}
  - name: new-cves
    type: git
    source:
      uri: git@github.com:cloudfoundry/buildpacks-ci.git
      branch: new-cve-notifications
      private_key: {{buildpacks-ci-binary-builds-private-key}}
  - name: stacks
    type: git
    source:
      uri: git@github.com:cloudfoundry/stacks.git
      branch: master
      private_key: {{buildpacks-ci-binary-builds-private-key}}

jobs:
  - name: New Releases
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: new-releases
        - get: check-interval
          trigger: true
      - task: notify
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: new-releases
            - name: buildpacks-ci
          run:
            path: buildpacks-ci/scripts/notifications/run
          params:
            SLACK_CHANNEL: {{dependency-notifier-slack-channel}}
            SLACK_WEBHOOK: {{dependency-notifier-slack-webhook}}
            GITHUB_USERNAME: {{github-username}}
            GITHUB_PASSWORD: {{github-password}}
            TRACKER_PROJECT_ID: 1042066
            TRACKER_API_TOKEN: {{pivotal-tracker-api-token}}
      - put: new-releases
        params:
          repository: notify/new-releases
          rebase: true
  - name: create tracker story for Monday Funday
    serial: true
    plan:
      - get: monday-funday
        trigger: true
      - get: buildpacks-ci
      - task: create tracker story
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
          run:
            path: buildpacks-ci/scripts/notifications/pivotal_tracker
            args: ['Pull latest changes from upstream', 'Check that there are no upstream changes that we are missing.']
          params:
            TRACKER_PROJECT_ID: 1042066
            TRACKER_API_TOKEN: {{pivotal-tracker-api-token}}
  - name: New CVEs
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: new-cves
        - get: check-interval
          trigger: true
        - get: stacks
          trigger: true
      - task: notify
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: new-cves
            - name: buildpacks-ci
            - name: stacks
          run:
            path: bash
            args:
              - -c
              - "cd buildpacks-ci/ && bundle && bundle exec ./scripts/notifications/check-cves"
          params:
            SLACK_CHANNEL: {{dependency-notifier-slack-channel}}
            SLACK_WEBHOOK: {{dependency-notifier-slack-webhook}}
            GITHUB_USERNAME: {{github-username}}
            GITHUB_PASSWORD: {{github-password}}
            TRACKER_PROJECT_ID: 1042066
            TRACKER_API_TOKEN: {{pivotal-tracker-api-token}}
            TRACKER_REQUESTER_ID: 765241
      - put: new-cves
        params:
          repository: notify/new-cves
          rebase: true
