---
resources:
  - name: buildpacks-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/buildpacks-ci
  - name: stacks
    type: git
    source:
      uri: git@github.com:cloudfoundry/stacks.git
      branch: master
      private_key: {{stacks-private-key}}
  - name: stack-s3
    type: s3
    source:
      bucket: pivotal-buildpacks
      regexp: cflinuxfs2-(.*).tar.gz
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}
  - name: receipt-s3
    type: s3
    source:
      bucket: pivotal-buildpacks
      regexp: cflinuxfs2_receipt-(.*)
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}
  - name: version
    type: semver
    source:
      bucket: pivotal-buildpacks
      key: versions/stack
      access_key_id: {{pivotal-buildpacks-s3-access-key}}
      secret_access_key: {{pivotal-buildpacks-s3-secret-key}}
  - name: deployments-buildpacks
    type: git
    source:
      uri: git@github.com:pivotal-cf/deployments-buildpacks
      private_key: {{deployments-private-key}}
      branch: master
  - name: stack-ci-8-cf-deployment
    type: bosh-deployment
    source:
      target: https://ec2-54-172-241-210.compute-1.amazonaws.com:25555
      username: admin
      password: {{bosh-lite-password}}
      deployment: cf-warden
      ignore_ssl: true
  - name: bosh-lite
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-lite
  - name: cf-release-runtime-passed
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-release
      branch: runtime-passed
  - name: cf-release-develop
    type: git
    source:
      uri: git@github.com:cloudfoundry/cf-release
      branch: develop
      private_key: {{cf-release-private-key}}
  - name: lite-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
  - name: docker-cflinuxfs2-rootfs
    type: docker-image
    source:
      repository: cloudfoundry/cflinuxfs2
      username: {{stacks-docker-username}}
      password: {{stacks-docker-password}}
      email: cf-buildpacks-eng@pivotal.io
  - name: stack-github-release
    type: github-release
    source:
      user: cloudfoundry
      repository: stacks
      access_token: {{buildpacks-github-token}}

jobs:
  - name: build-rootfs
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: stacks
        - get: version
          params: { bump: minor, pre: rc }
      - task: make-rootfs
        config:
          platform: linux
          image: docker:///jpetazzo/dind
          inputs:
            - name: buildpacks-ci
            - name: stacks
            - name: version
          run:
            path: buildpacks-ci/scripts/stacks/make-rootfs
        privileged: true
      - put: stack-s3
        params:
          from: make-rootfs/stacks/cflinuxfs2-(.*).tar.gz
          to: /rootfs/
      - put: receipt-s3
        params:
          from: make-rootfs/cflinuxfs2_receipt-(.*)
          to: /rootfs/
      - put: version
        params: { file: version/number }
  - name: deploy-cf-to-stack-ci-8
    serial: true
    serial_groups: [ stack-ci-8 ]
    plan:
      - aggregate:
        - get: deployments-buildpacks
        - get: bosh-lite
        - get: buildpacks-ci
        - get: cf-release
          resource: cf-release-runtime-passed
        - get: lite-stemcell
        - get: stack-s3
          passed: [ build-rootfs ]
        - get: version
          passed: [ build-rootfs ]
          trigger: true
        - get: receipt-s3
          passed: [ build-rootfs ]
        - get: stacks
          passed: [ build-rootfs ]
      - task: generate-manifest
        file: buildpacks-ci/tasks/make-manifest.yml
        config:
          params:
            DEPLOYMENT_NAME: stack-ci-8
            CF_CI_PASSWORD: {{ci-cf-password}}
        privileged: true
      - put: deployments-buildpacks
        params:
          repository: generate-manifest/deployments-buildpacks
      - task: create-stack-release
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
            - name: cf-release
            - name: stack-s3
          run:
            path: buildpacks-ci/scripts/stacks/create-release
        privileged: true
      - put: stack-ci-8-cf-deployment
        params:
          manifest: deployments-buildpacks/deployments/stack-ci-8/manifest.yml
          stemcells: [lite-stemcell/*.tgz]
          releases: [create-stack-release/cf-release/dev_releases/cf/*.tgz]
  - name: test-rootfs
    serial: true
    serial_groups: [ stack-ci-8 ]
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: cf-release-runtime-passed
          passed: [ deploy-cf-to-stack-ci-8 ]
        - get: deployments-buildpacks
        - get: stack-s3
          passed: [ deploy-cf-to-stack-ci-8 ]
        - get: version
          passed: [ deploy-cf-to-stack-ci-8 ]
          trigger: true
        - get: receipt-s3
          passed: [ deploy-cf-to-stack-ci-8 ]
        - get: stacks
          passed: [ deploy-cf-to-stack-ci-8 ]
      - task: cats
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
            - name: cf-release-runtime-passed
              path: cf-release
            - name: deployments-buildpacks
          run:
            path: buildpacks-ci/scripts/stacks/cats
          params:
            CI_CF_USERNAME: {{ci-cf-username}}
            CI_CF_PASSWORD: {{ci-cf-password}}
        privileged: true
  - name: shipit
    serial: true
    plan:
      - aggregate:
        - get: buildpacks-ci
        - get: stack-s3
          passed: [ test-rootfs ]
        - get: receipt-s3
          passed: [ test-rootfs ]
        - get: stacks
          resource: stacks
          passed: [ test-rootfs ]
        - get: version
          passed: [ test-rootfs ]
          params: { bump: final }
      - task: update-receipt
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
            - name: receipt-s3
            - name: stacks
            - name: version
          run:
            path: buildpacks-ci/scripts/stacks/update-receipt
      - put: stacks
        params:
          repository: update-receipt/stacks
          tag: version/number
      - put: version
        params: { file: version/number }
  - name: upload-to-github
    serial: true
    plan:
      - aggregate:
        - get: stack-s3
          passed: [ shipit ]
        - get: version
          trigger: true
          passed: [ shipit ]
          params: { bump: final }
      - task: rename-blob
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: stack-s3
            - name: version
          run:
            path: /bin/sh
            args: ['-c', 'mv stack-s3/cflinuxfs2-*.tar.gz cflinuxfs2-`cat version/number`.tar.gz']
      - put: stack-github-release
        params:
          name: version/number
          tag: version/number
          globs:
            - rename-blob/cflinuxfs2-*.tar.gz
  - name: upload-to-docker
    serial: true
    plan:
      - aggregate:
        - get: stack-s3
          passed: [ shipit ]
        - get: version
          trigger: true
          passed: [ shipit ]
      - put: docker-cflinuxfs2-rootfs
        params:
          import_file: stack-s3/cflinuxfs2-*.tar.gz
      - put: docker-cflinuxfs2-rootfs
        params:
          load: docker-cflinuxfs2-rootfs
          tag: version/number
  - name: upload-to-cf-release
    serial: true
    plan:
      - aggregate:
        - get: stack-s3
          passed: [ shipit ]
        - get: cf-release-develop
        - get: buildpacks-ci
        - get: version
          trigger: true
          passed: [ shipit ]
        - get: receipt-s3
          passed: [ shipit ]
      - task: upload
        config:
          platform: linux
          image: docker:///cfbuildpacks/ci
          inputs:
            - name: buildpacks-ci
            - name: cf-release-develop
              path: cf-release
            - name: stack-s3
            - name: receipt-s3
            - name: version
          run:
            path: buildpacks-ci/scripts/stacks/upload-to-cf-release
          params:
            ACCESS_KEY_ID: {{blobstore-access-key}}
            SECRET_ACCESS_KEY: {{blobstore-secret-key}}
        privileged: true
      - put: cf-release-develop
        params:
          repository: upload/cf-release
          rebase: true
