[package]
name = "depwatcher"
version = "0.1.0"
authors = ["Dave Goddard <dave@goddard.id.au>"]

[[bin]]
name = "check"
path = "src/check.rs"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.8.1"
error-chain = "0.11.0"
semver = "*"

