---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/ci
inputs:
  - name: buildpacks-ci
  - name: bp-supply
run:
  path: bash
  args:
    - -cl
    - |
      set -ex
      mkdir -p /go/src/github.com/cloudfoundry/
      cp -r bp-supply /go/src/github.com/cloudfoundry/
      cd /go/src/github.com/cloudfoundry/bp-supply
      (cd vendor/github.com/onsi/ginkgo && go install)

      ginkgo


