---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/ci
inputs:
  - name: buildpacks-ci
  - name: capi-release
  - name: bal-develop
outputs:
  - name: capi-release-artifacts
run:
  path: bash
  args:
    - -cl
    - buildpacks-ci/tasks/create-capi-release/run.rb
