---
deployment-name: bp-ci-7b
resource-pool: cf-lts-environments
cf-version: 208
generate-manifest: buildpacks-ci/tasks/make-manifest.yml
generated-manifest-location: generate-manifest/cf-release/bosh-lite/manifests/cf-manifest.yml
