---
deployment-name: lts-2.buildpacks.ci
resource-pool: cf-lts-environments
cf-version: 225
generated-manifest-location: generate-manifest/cf-release/bosh-lite/manifests/cf-manifest.yml
cf-manifest-location: deployments-buildpacks/deployments/lts-2.buildpacks.ci/manifest.yml
